[package]
name = "bcm2835-sys"
version = "0.1.0"
authors = ["abhicv <abhijithcheruvery@gmail.com>"]
build = "build.rs"
link = "bcm2835"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
